apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack2matrix
  labels:
    app: slack2matrix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slack2matrix
  template:
    metadata:
      labels:
        app: slack2matrix
    spec:
      automountServiceAccountToken: false
      containers:
      - name: slack2matrix
        image: justinbarrick/matrixctl:v0.0.4
        env:
        - name: MATRIX_CONFIG
          value: /app/config.json
        # - name: MATRIX_CHAN
        #   value: defaultchannel
        volumeMounts:
        - name: config-volume
          mountPath: /app/config.json
          subPath: config.json
      volumes:
      - name: config-volume
        secret:
          secretName: slack2matrix
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
        - 1.1.1.1
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: slack2matrix
  namespace: slack2matrix
spec:
  podSelector: {}
  ingress:
  - {}
  egress:
  - to:
    - ipBlock:
        cidr: "0.0.0.0/0"
        except:
        - "10.0.0.0/8"
        - "192.168.0.0/16"
        - "172.16.0.0/12"
---
apiVersion: v1
kind: Service
metadata:
  name: slack2matrix
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    app: slack2matrix
---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: slack2matrix
#  labels:
#    app: slack2matrix
#  annotations:
#    kubernetes.io/ingress.class: "nginx"
#spec:
#  rules:
#  - host: slack2matrix.example.com
#    http:
#      paths:
#      - path: /
#        backend:
#          serviceName: slack2matrix
#          servicePort: 8000
#  tls:
#  - hosts:
#    - slack2matrix.example.com
#    secretName: slack2matrix-tls
#---
